# ssh-keygen -t rsa "740302323@qq.com"

name: Deploy project

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        # 先删除
        # ARGS: '-avzr --delete'
        SOURCE: "./dist/"
        # IP
        SCRIPT_BEFORE: ls
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: "root"
        TARGET: "/home/nginx/html/dist"